name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include: [
            { name: Chrome++_x86, arch: x86 },
            { name: Chrome++_x64, arch: x64 },
        ]

    name: ${{ matrix.name }}

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
      with:
        submodules: 'true'

    - name: setup VC-LTL
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget install VC-LTL

    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: configure
      run: xmake f -a ${{ matrix.arch }}

    - name: build
      run: xmake

    - name: upload
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ${{ matrix.name }}
        path: build/release

    - name: upload
      uses: actions/upload-artifact@v3.1.3
      with:
        name: chrome++.ini
        path: src
